# Generated by Django 4.2.9 on 2025-02-08 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoboothuser',
            name='address',
        ),
        migrations.CreateModel(
            name='ShopAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('shop_phone', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photobooth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='photobooth.photoboothuser')),
            ],
            options={
                'verbose_name_plural': 'Shop Addresses',
            },
        ),
    ]
