# Generated by Django 4.2.9 on 2025-03-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0003_remove_photoboothuser_address_shopaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoboothuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photoboothuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photoboothuser',
            name='legal_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photoboothuser',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='photoboothuser',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Herr', 'Herr'), ('Frau', 'Frau')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='photoboothuser',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
