# Generated by Django 4.2.9 on 2025-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0004_photoboothuser_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopaddress',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shopaddress',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
    ]
