# Generated by Django 4.2.9 on 2025-03-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0005_shopaddress_latitude_shopaddress_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopaddress',
            name='shop_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
