# Generated by Django 4.2.9 on 2025-03-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0006_alter_shopaddress_shop_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoboothuser',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Herr', 'Herr'), ('Frau', 'Frau'), ('Divers', 'Divers'), ('Keine Anrede', 'Keine Anrede')], max_length=12, null=True),
        ),
    ]
