# Generated by Django 4.2.9 on 2025-03-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0008_photoboothuser_employer_photoboothuser_owner_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopaddress',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
