# Generated by Django 4.2.9 on 2025-03-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0009_shopaddress_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoboothuser',
            name='licensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photoboothuser',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
