# Generated by Django 4.2.9 on 2025-04-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0010_photoboothuser_licensed_photoboothuser_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoboothuser',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
