# Generated by Django 4.2.9 on 2025-04-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0011_alter_photoboothuser_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoboothuser',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('employee', 'Employee')], default='owner', max_length=10),
        ),
        migrations.AlterField(
            model_name='shopaddress',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
