name: Deploy Django to EC2

on:
  push:
    branches:
      - master   # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/E-passtransfer/
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart e-passtransfer  # (Or your gunicorn service name)
